cuda_visible_devices = '0'
device = 'cuda'
# device = 'cpu'
# model_name = 'cambridgeltl/SapBERT-from-PubMedBERT-fulltext'
# model_name = '/home/yangye/BioCreative/model/sapbert_hpo_5epoch'
model_name = '/home/yangye/BioCreative/model/sapbert_hpo_30epoch/checkpoint_26'
checkpoint_dir = './checkpoint(SapBERT)_5.30_CLS'
data_path = './dataset'
